### ISSUE TITLE
[Feature Request] SD-WebUIの拡張機能としての提供

### ISSUE THREAD

**Issue by mattyamonaca** [tori29umai0123/ShadowGenerator#1]
素晴らしい機能を提供いただきありがとうございます。
こちらの機能ですが、Stable Diffusion WebUIの拡張機能として提供される予定はありますでしょうか？
SD WebUIが導入されている事が前提の機能とのことなので、拡張機能として使えると非常に便利かなと思っております。

必要であれば拡張機能として提供するためのコードをこちらで用意することも可能ですので、ご検討いただければと思います。

**Comment by tori29umai0123** [comment]
＞必要であれば拡張機能として提供するためのコードをこちらで用意することも可能ですので、ご検討いただければと思います。
ありがたいです！私も拡張機能として公開できたらいいなぁと思いつつ、そのためには勉強が必要だと思って見送っていました。可能でありましたら是非お願いしたいです。
